name: Docker Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-docker@v1
      - name: Build image
        run: docker build -t task-schedule-api .
      - name: Push image
        run: docker push task-schedule-api
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Docker Hub
        run: docker run --rm -it -p 5000:5000 task-schedule-api
